### ISSUE TITLE
Verified card get ADDRESS_VERIFICATION_FAILURE error when processing Square Payment. 

### ISSUE THREAD

**Issue by royrakesh** [square/square-php-sdk#28] opened 2020-10-21 06:38 UTC
Hi
First, we process the card details a via Square Js then call verifyBuyer with verification details and payment info.
If above success then sends the Card Noce and Verification Token to the backend to process the Payment. 

### Issue
We successfully verify the buyer got the card token/customer-id (When creating customer) then we get **ADDRESS_VERIFICATION_FAILURE**   error when we charge the amount. How can we get Address error when we already pass verifyBuyer and able to save the card.

This is just one issue. there are lots of blocking from square and error message doesn't describe anything helpful. 

1. Js Code

![image](https://user-images.githubusercontent.com/15174104/96681934-ab4df580-1395-11eb-8ad7-d8db1f433f12.png)

2. Payment Process

![image](https://user-images.githubusercontent.com/15174104/96682097-f9fb8f80-1395-11eb-8a51-8e181112f3ce.png)

**Comment by StephenJosey** [comment] 2020-10-21 16:05
`verifyBuyer` doesn't confirm if the card is completely valid, I believe. It checks to see if the bank is requiring the customer to verify that they themselves are using the card. If the customer doesn't receive a pop-up asking them to confirm their identity, then nothing really was checked (ie the bank didn't require it to be confirmed).

`ADDRESS_VERIFICATION_FAILURE` means "The card issuer declined the request because the postal code is invalid." as can be seen here in our documentation: https://developer.squareup.com/reference/square/payments-api/create-payment#error-descriptions.

**Comment by royrakesh** [comment] 2020-10-22 08:24
Hi this is the address used 
```
123, Antrim Road
Glengormley
Antrim
BT36 5EQ
```
This is a valid address and valid postcode. 
Then how API is responding with an errorr. 
The Error response via API I not sufficient.

**Comment by StephenJosey** [comment] 2020-10-22 16:50
The `CreatePayment` request checks to see if the card is valid or not. The `verifyBuyer` just checks to see if the bank is requiring verification as far as I understand it. Do you have the `payment_id` so I can take a look on our end? Maybe something else is going on, or maybe I'm misunderstanding and can check with some other folks.

**Comment by royrakesh** [comment] 2020-11-07 05:17
Hi as the payment is failed so I don't have any payment id.
Your SDK need lots of Bug Fix. First thing you should do is Erro handling. 
Proper Error should return on specific requests. 

**verifyBuyer** should check the Buyer as it states it not possible to show the error of wrong address after we save a card on the file and card details are checked from Bank.

**Comment by StephenJosey** [comment] 2020-11-09 17:39
When a payment fails in v2 (CreatePayment), it still creates a payment, with an error inside the payment object, so you should have a payment id. The SDK puts the errors inside the API response like `$apiResponse->getErrors()`, so I'm not sure what you mean by error handling. The response knows if it was successful or not:
```
if ($apiResponse->isSuccess()) {
...
```
For your last paragraph, can you clarify what you mean? You saved the card on file successfully, but then when you called `CreatePayment` you received this error? That does seem a bit odd, if that's the case. Can you provide any details so I can look into this?

- Customer id?
- Location id?
- Application id?

**Comment by sseaman** [comment] 2020-11-24 16:33
Closing issue as it looks to be resolved.  Please feel free to reopen if you have additional questions.

**Closed by sseaman** 2020-11-24 16:33 UTC
