### ISSUE TITLE
Description set using `setDescriptionHtml` does not show up in the sandbox dashboard

### ISSUE THREAD

**Issue by Sidsector9** [square/square-php-sdk#127] opened 2024-01-08 09:05 UTC
## **ATTENTION**
This issue template is for **bugs** or **documentation** errors in this SDK Repo. Please direct all technical support questions, feature requests, API-related issues, and general discussions to our Square-supported developer channels. For public support, [join us in our BuildWithSquare Slack](https://squ.re/slack) or [post in our Developer Forums](https://developer.squareup.com/forums). For private support, [contact our Developer Success Engineers](https://squareup.com/help/us/en/contact?panel=BF53A9C8EF68) directly.

**Describe the bug**

We're trying to migrate from the deprecated `setDescription` to `setDescriptionHtml` but the problem is that the description set via the latter isn't visible in the dashboard, however the former works as expected.

**Expected behavior**

Description set using the `setDescriptionHtml` method should be visible in the dashboard.

**Square SDK version**
We're currently using 29.0.0.20230720
But we tested with 33.1.0.20231213 as well

**Additional context**

**Comment by zenmasterjobo** [comment] 2024-01-08 22:07
hi @Sidsector9 - sorry to hear about the issue you are running into. Can you help me understand the use-case a little bit better? You're updating a catalog item's description using that new method but that description then doesn't show up in the Square seller's dashboard? If that's the case do you mean that it's just not setting the description at all? E.g. after you use the method to update the description, if you call the API, the description is not set? Or is it purely a problem in the seller dashboard?

**Comment by Sidsector9** [comment] 2024-01-09 07:38
@zenmasterjobo answering your questions:

> You're updating a catalog item's description using that new method but that description then doesn't show up in the Square seller's dashboard?

That's correct.

> After you use the method to update the description, if you call the API, the description is not set? Or is it purely a problem in the seller dashboard?

I just confirmed in the API explorer and I can see the description there, but not in the dashboard.

**Comment by zenmasterjobo** [comment] 2024-01-09 18:29
Hi @Sidsector9 this looks like an error in our Sandbox dashboard. I confirmed that this field is correctly updating and showing in the production seller dashboard. I'm going to contact our team that manages the sandbox environment and have them fix this issue. To be clear this is a not a PHP sdk issue. 

I will close this ticket after I get confirmation on a fix. Thanks for bringing this to our attention!

**Comment by Sidsector9** [comment] 2024-01-09 19:34
Sounds good! Thanks for looking into this.

**Comment by zenmasterjobo** [comment] 2024-01-10 00:28
Hey @Sidsector9, we have updated sandbox to fix the issue. You may need to run the update on the item again to see the changes take effect.

Let me know if you have more issues!

**Closed by zenmasterjobo** 2024-01-10 00:28 UTC

**Comment by Sidsector9** [comment] 2024-01-17 06:36
@zenmasterjobo can you please reopen this issue?

When you set description using `setDescriptionHtml()` which has more than `4096` characters, the `description_html` field shows the entire content but the `description` field trims it to 4096 characters.

In the Square sandbox dashboard, the description is trimmed as well. The `description_html` and `description_plaintext` fields are in sync but the `description` field is not. Just wanted to confirm if this is by design?

Please see the response below:

```json
{
  "objects": [
    {
      "type": "ITEM",
      "id": "YNSE7OQWYKAIEAZTX5WFC25M",
      "updated_at": "2024-01-17T06:33:55.928Z",
      "created_at": "2024-01-17T06:23:27.528Z",
      "version": 1705473235928,
      "is_deleted": false,
      "present_at_all_locations": false,
      "present_at_location_ids": [
        "LM6079RG73WD2"
      ],
      "item_data": {
        "name": "Sumit",
        "description": "Children, the embodiment of innocence and wonder, hold the promise of a brighter tomorrow. In their laughter, we find echoes of pure joy, unburdened by the complexities of adulthood. Observing kids is akin to witnessing a canvas being painted with the vibrant hues of curiosity and boundless imagination. Every discovery, from the fluttering of a butterfly to the dance of raindrops, is a profound revelation for them. As caregivers and mentors, our role extends beyond providing mere sustenance; it involves nurturing the seeds of compassion, resilience, and creativity that reside within these young souls.\nIn the world of children, play is not merely a pastime but a medium through which they explore their surroundings and make sense of the unfolding universe. A simple cardboard box transforms into a spaceship, and a backyard becomes a jungle teeming with imaginary creatures. Their uninhibited enthusiasm is a reminder to adults to approach life with the same openness and willingness to see magic in the mundane.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nChildren are not only the future but also the guardians of our humanity. Through their eyes, we rediscover the world's beauty, its flaws, and the immense capacity for love that binds us all. As we navigate the intricate tapestry of parenthood, education, and societal influence, let us be mindful of the profound impact our actions have on these impressionable minds. For in the laughter of a child, we find the melody of hope, urging us to build a world where every child can flourish, unfurling their wings to reach new heights.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for t",
        "is_taxable": true,
        "variations": [
          {
            "type": "ITEM_VARIATION",
            "id": "M2AQXPEC6T7OMYWLQ4YSLVKW",
            "updated_at": "2024-01-17T06:23:27.528Z",
            "created_at": "2024-01-17T06:23:27.528Z",
            "version": 1705472607528,
            "is_deleted": false,
            "present_at_all_locations": false,
            "present_at_location_ids": [
              "LM6079RG73WD2"
            ],
            "item_variation_data": {
              "item_id": "YNSE7OQWYKAIEAZTX5WFC25M",
              "name": "",
              "sku": "sumit",
              "ordinal": 0,
              "pricing_type": "FIXED_PRICING",
              "price_money": {
                "amount": 19900,
                "currency": "USD"
              },
              "track_inventory": false,
              "sellable": true,
              "stockable": true
            }
          }
        ],
        "product_type": "REGULAR",
        "categories": [
          {
            "id": "QMWN4BX52HM7MPQK4FN5526X",
            "ordinal": -2251524935778304
          }
        ],
        "description_html": "Children, the embodiment of innocence and wonder, hold the promise of a brighter tomorrow. In their laughter, we find echoes of pure joy, unburdened by the complexities of adulthood. Observing kids is akin to witnessing a canvas being painted with the vibrant hues of curiosity and boundless imagination. Every discovery, from the fluttering of a butterfly to the dance of raindrops, is a profound revelation for them. As caregivers and mentors, our role extends beyond providing mere sustenance; it involves nurturing the seeds of compassion, resilience, and creativity that reside within these young souls.\nIn the world of children, play is not merely a pastime but a medium through which they explore their surroundings and make sense of the unfolding universe. A simple cardboard box transforms into a spaceship, and a backyard becomes a jungle teeming with imaginary creatures. Their uninhibited enthusiasm is a reminder to adults to approach life with the same openness and willingness to see magic in the mundane.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nChildren are not only the future but also the guardians of our humanity. Through their eyes, we rediscover the world&#39;s beauty, its flaws, and the immense capacity for love that binds us all. As we navigate the intricate tapestry of parenthood, education, and societal influence, let us be mindful of the profound impact our actions have on these impressionable minds. For in the laughter of a child, we find the melody of hope, urging us to build a world where every child can flourish, unfurling their wings to reach new heights.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow. Test with Sid. In-woo with the trunk branch.",
        "description_plaintext": "Children, the embodiment of innocence and wonder, hold the promise of a brighter tomorrow. In their laughter, we find echoes of pure joy, unburdened by the complexities of adulthood. Observing kids is akin to witnessing a canvas being painted with the vibrant hues of curiosity and boundless imagination. Every discovery, from the fluttering of a butterfly to the dance of raindrops, is a profound revelation for them. As caregivers and mentors, our role extends beyond providing mere sustenance; it involves nurturing the seeds of compassion, resilience, and creativity that reside within these young souls.\nIn the world of children, play is not merely a pastime but a medium through which they explore their surroundings and make sense of the unfolding universe. A simple cardboard box transforms into a spaceship, and a backyard becomes a jungle teeming with imaginary creatures. Their uninhibited enthusiasm is a reminder to adults to approach life with the same openness and willingness to see magic in the mundane.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nChildren are not only the future but also the guardians of our humanity. Through their eyes, we rediscover the world's beauty, its flaws, and the immense capacity for love that binds us all. As we navigate the intricate tapestry of parenthood, education, and societal influence, let us be mindful of the profound impact our actions have on these impressionable minds. For in the laughter of a child, we find the melody of hope, urging us to build a world where every child can flourish, unfurling their wings to reach new heights.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow.\nYet, in our efforts to guide and protect, we must tread lightly, allowing room for their spirits to soar. Each child is a unique constellation of traits, dreams, and potential, waiting to be unfolded. The responsibility to cultivate a nurturing environment lies not only in our hands but also in the collective consciousness of society. It involves fostering inclusive educational systems, promoting emotional intelligence, and championing the right of every child to dream, learn, and grow. Test with Sid. In-woo with the trunk branch.",
        "is_archived": false,
        "reporting_category": {
          "id": "QMWN4BX52HM7MPQK4FN5526X",
          "ordinal": -2251524935778304
        }
      }
    }
  ]
}
```

**Comment by zenmasterjobo** [comment] 2024-01-18 19:36
hi @Sidsector9,

unfortunately this is operating as expected. Because the description field is deprecated,  we are pushing for users to move over to the `description_html` and the `description_plaintext`.

If you use is running into issues while trying to move over to using these fields, let me know

**Comment by Sidsector9** [comment] 2024-01-19 17:29
Thanks for responding @zenmasterjobo. The issue we are facing is that the sandbox dashboard displays the trimmed description from the `description` field instead of `description_html` or `description_plaintext`. Is it supposed to be this way?

**Comment by zenmasterjobo** [comment] 2024-01-22 19:23
hey @Sidsector9, sorry for the delay on this one. Ah yeah, that's definitely a bug - this should now be fixed in Sandbox. Can you check again and let me know that it's working now?

**Comment by Sidsector9** [comment] 2024-01-23 15:51
@zenmasterjobo thanks for looking into it. Our QA has confirmed it is working as expected!
